src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;



    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_city;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $user_status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_gender;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $confirmationToken;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function getName(): string {
        return $this->user_name;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }

    public function getUserAvatar(): ?string
    {
        return $this->user_avatar;
    }

    public function setUserAvatar(?string $user_avatar): self
    {
        $this->user_avatar = $user_avatar;

        return $this;
    }

    public function getUserCity(): ?string
    {
        return $this->user_city;
    }

    public function setUserCity(string $user_city): self
    {
        $this->user_city = $user_city;

        return $this;
    }

    public function getUserStatus(): ?string
    {
        return $this->user_status;
    }

    public function setUserStatus(string $user_status): self
    {
        $this->user_status = $user_status;

        return $this;
    }

    public function getUserGender(): ?string
    {
        return $this->user_gender;
    }

    public function setUserGender(string $user_gender): self
    {
        $this->user_gender = $user_gender;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmationToken;
    }

    public function setConfirmationToken(?string $confirmationToken): self
    {
        $this->confirmationToken = $confirmationToken;

        return $this;
    }
}

templates/home/home.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{asset('web/css/home.css')}}">
    <style>
        body {
            overflow: hidden!important;
            background: url("{{ asset('web/images/backgroundImage.jpg') }}");
            background-repeat: no-repeat;
            background-size: cover;
            background-position-y: -100px;
            background-position-x: 20px;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container main-section">
        <div id="holaMundo" class="row">
            <div class="col-md-3 col-sm-3 col-xs-12 left-sidebar">
                <div class="input-group searchbox" style="background: orange">


                    <div class="right-header-img">
                        <img src="{{ app.user.userAvatar }}" alt="profile pic">
                    </div>
                    <div class="right-header-detail">

                            <p></p>
                        <a href="{{ path('profile') }}"><span style="font-size: large; color: black">{{ app.user.name }}</span></a>&nbsp &nbsp
                            <a href="{{ path('logOutFromApp') }}" class="btn btn-danger">Logout</a>


                    </div>
                    <p id="newMessages"></p>
                </div>
                <div class="left-chat" style="height: 524px; background: cornflowerblue;">
                    <ul>
                        {% for elem in others %}
                        <li>
                            <!--
                            <div class='chat-left-img'>
                                <img src='$user_profile'>
                            </div>
                            <div class='chat-left-detail'>
                                <p><a href='home.php?user_email=$user_email'>$user_name</a></p>";
                                if($login == 'Online'){
                                echo "<span><i class='fa fa-circle' aria-hidden='true'></i> Online</span>";
                                }else{
                                echo "<span><i class='fa fa-circle-o' aria-hidden='true'></i> Offline</span>";
                                }

                                "
                            </div> -->
                            <div class='chat-left-img'>
                                <img src='{{ elem.userAvatar }}'>
                            </div>
                            <div class='chat-left-detail'>
                                <p><a href="javascript:loadDetails({{ elem.id }})" style="font-size: medium; color: darkblue" >{{ elem.name }}</a></p>
                                <span id="{{ elem.id }}">
                                {% if elem.userStatus == 'offline' %}
                                    <span style="color: white"><i class='fa fa-circle-o' aria-hidden='true'></i> Offline</span>
                                {% endif %}
                                    {% if elem.userStatus == 'online' %}
                                        <span><i class='fa fa-circle' aria-hidden='true'></i> Online</span>
                                    {% endif %}
                                </span>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div style="visibility: hidden" id="messages-bar" class="col-md-9 col-sm-9 col-xs-12 right-sidebar">
                <div class="row">

                    <!-- getting the user data on which user click -->

                    <div class="col-md-12 right-header">
                        <div class="right-header-img">
                            <img id="clicked-user" >
                        </div>
                        <div class="right-header-detail">
                            <form method="post">
                                <p id="clicked-user-name"></p>
                                <span></span>&nbsp &nbsp

                            </form>
                            <div style="width: 20px"></div>

                        </div>
                    </div>

                </div>
                <div class="row">
                    <div id="scrolling_to_bottom" class="col-md-12 right-header-contentChat" style="height: 453px;">
                        <ul id="messagesBox"></ul>
                    </div>
                </div>
                <div class="row">
                    <div style="height: 85px" class="col-md-4 right-chat-textbox">

                        <form id="myform">
                            <input id="msg-content" autocomplete="off" type="text" name="msg-content" placeholder="Write your message...">
                            <div class="image_upload">
                                <label for="fileToUpload">
                                    <img src="{{ asset('web/images/uploadImage.png') }}"/>
                                </label>
                                <!--Input for file or image-->
                                <input type="file" name="fileToUpload" id="fileToUpload">
                            </div>
                            <button class="btn"  name="submit"><i class="fa fa-telegram" aria-hidden="true"></i></button>

                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script>
        let current = {{ app.user.id }};
        let currentName = {{ app.user.name|json_encode()|raw }};
        let other;
        let otherName;
        let show = false;

        function loadDetails(id) {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    let jsonResponse = JSON.parse(this.responseText);
                    other = jsonResponse['user']['id'];
                    otherName = jsonResponse['user']['name'];
                    let allMessages = jsonResponse['allMessages'];
                    console.log(allMessages);
                    console.log(current);
                    console.log(currentName);
                    console.log(other);
                    console.log(otherName);
                    updateMessages(current, other, allMessages);

                    document.getElementById('clicked-user').src = jsonResponse['user']['userAvatar'];
                    document.getElementById('clicked-user-name').innerHTML = "<a href='/showProfileOther/"+other+"'>"+jsonResponse['user']['name']+"</a>";

                    if(show == false) {
                        show = true;
                        document.getElementById('messages-bar').style.visibility = 'visible'
                    }

                }
            };
            xhttp.open("GET", "/loadDetails/"+id, true);
            xhttp.send();
        }


            function inicio() {
                newMessages();
                setInterval(() => {
                    if(other != undefined) {
                        loadDetails(other);
                    }
                    newMessages();
                    onlineStatus();
                },10000);
                console.log(currentName)
                document.getElementById('myform').addEventListener('submit', function(e) {
                    e.preventDefault();
                    const formData = new FormData(this);
                    var xhttp = new XMLHttpRequest();
                    xhttp.onreadystatechange = function() {
                        if (this.readyState == 4 && this.status == 200) {
                            let jsonResponse = JSON.parse(this.responseText);
                            console.log(jsonResponse)
                            loadDetails(other);

                        }
                    };
                    xhttp.open("post", "/sendMessage/"+other, true);
                    xhttp.send(formData);
                    this.reset();

                })
            }

            function updateMessages(current, other, allMessages) {

                sendBox = document.getElementById('messagesBox');
                let stringAllMessages = '';
                allMessages.forEach((message, index) => {

                    let senderId = message['senderId'];
                    let receiverId = message['receiverId'];
                    if(senderId == current && receiverId == other) {
                        if(message['msgType'] != 'text'){
                            stringAllMessages += "<li><div class='rightside-right-chat'> <span>"+currentName+" <small>"+message['dateTime']+"</small> </span><br><br> <p><a href="+"../web/images/"+message['attachments']+"><img onerror='this.onerror=null;this.src=`../web/images/file.png`' width='60px' height='60px' src="+"../web/images/"+message['attachments']+" alt='' ></a>"+" "+message['msgContent']+"</p> </div></li>"
                        } else {
                            stringAllMessages += "<li><div class='rightside-right-chat'> <span>"+currentName+" <small>"+message['dateTime']+"</small> </span><br><br> <p>"+message['msgContent']+"</p> </div></li>"
                        }

                    } else if(senderId == other && receiverId == current) {
                        if(message['msgType'] != 'text'){
                            stringAllMessages += "<li><div class='rightside-left-chat'> <span>"+otherName+" <small>"+message['dateTime']+"</small> </span><br><br> <p><a href="+"../web/images/"+message['attachments']+"><img onerror='this.onerror=null;this.src=`../web/images/file.png`' width='60px' height='60px' src="+"../web/images/"+message['attachments']+" alt='' ></a>"+" "+message['msgContent']+"</p> </div></li>"
                        } else {
                            stringAllMessages += "<li><div class='rightside-left-chat'> <span>"+otherName+" <small>"+message['dateTime']+"</small> </span><br><br> <p>"+message['msgContent']+"</p> </div></li>"
                        }
                    }
                }

            )

                sendBox.innerHTML = stringAllMessages;
                var objDiv = document.getElementById("scrolling_to_bottom");
                objDiv.scrollTop = objDiv.scrollHeight;
        }

        function newMessages() {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    let jsonResponse = JSON.parse(this.responseText);
                    console.log(jsonResponse)
                    document.getElementById("newMessages").innerText = jsonResponse['total'].length+" new messages";

                }
            };
            xhttp.open("GET", "/newMessages", true);
            xhttp.send();
        }

        function onlineStatus() {
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    let jsonResponse = JSON.parse(this.responseText);
                    jsonResponse = jsonResponse['all']
                    jsonResponse.forEach((element, index) => {
                        let id = element['id'];
                        console.log(id)
                        let status = element['userStatus'];


                        if(id != current) {
                            let span = document.getElementById(id);
                            if(status == 'offline') {
                                span.innerHTML = `<span style="color: white"><i class='fa fa-circle-o' aria-hidden='true'></i> Offline</span>`
                            } else {
                                span.innerHTML = `<span><i class='fa fa-circle' aria-hidden='true'></i> Online</span>`
                            }
                        }


                    })
                }
            };
            xhttp.open("GET", "/onlineStatus", true);
            xhttp.send();
        }

        window.onload = inicio();


    </script>

{% endblock %}

templates/home/profile.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="css/.css">
{% endblock %}
{% block body %}
    <div style="height: 60px; background: black;color: white;padding: 20px; font-weight: bold "><a style="color: white; font-size: 2rem; text-decoration: none" href="{{ path('home') }}">konneck</a></div>
    {% for message in app.flashes('error') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="row">

        <div class="col-sm-8">
            <form action="{{ path('modifyProfile', {id: app.user.id}) }}" method="post" enctype="multipart/form-data">
                <table class="table table-bordered table-hover">
                    <tr align="center">
                        <td colspan="6" class="active"><h2>Change Account Settings</h2></td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold;">Change Your Username</td>
                        <td>
                            <input class="form-control" type="text" name="u_name" required="required" value="{{ app.user.name }}"/>
                        </td>
                    </tr>

                    <tr><td><img width="200px" height="200px" src="{{ app.user.userAvatar }}" alt=""></td><td><input name="u_avatar" type="file" class="btn btn-default" accept="image/*" style="text-decoration: none;font-size: 15px;"></td></tr>

                    <tr>
                        <td style="font-weight: bold;">Email</td>
                        <td>
                            <input class="form-control" type="email" name="u_email" required="required" value="{{ app.user.email }}" disabled></td>
                    </tr>


                    <tr>
                        <td style="font-weight: bold;">City</td>
                        <td>
                            <input class="form-control" type="text" value="{{ app.user.userCity }}" disabled>
                        </td>

                    </tr>
                    <tr>
                        <td>

                        </td>
                        <td>
                            <select class="form-control" name="u_city">
                                <option></option>
                                <option>Madrid</option>
                                <option>Barcelona</option>
                                <option>Valencia</option>
                                <option>Málaga</option>
                                <option>Córdoba</option>
                            </select>
                        </td>
                    </tr>



                    <tr>
                        <td style="font-weight: bold;">Gender</td>
                        <td><input class="form-control" type="text" value="{{ app.user.userGender}}" disabled></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <select class="form-control" name="u_gender">
                                <option></option>
                                <option>Male</option>
                                <option>Female</option>
                                <option>Other</option>
                            </select>
                        </td>
                    </tr>



                    <tr><td style="font-weight: bold;">Change password</td>
                        <td>Current Password: <input minlength="6" name="u_pass" type="password"><br>New Password: <input name="new_pass" minlength="6" type="password"></td></tr>

                    <tr align="center">
                        <td colspan="6">
                            <input class="btn btn-info" style="width: 250px;" type="submit" name="update" value="Update"/>
                        </td>
                    </tr>
                </table>
            </form>



            </div>
            <div class="col-sm-2">
                </div>
                </div>

{% endblock %}

templates/home/profileOther.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<style>
    p {
        font-size: 20px;
    }
    div {
        width: 500px;
        margin: auto !important;
        margin-top: 20px !important;
        text-align: center;
    }
</style>

{% endblock %}
{% block body %}
<div style="margin: 100px; border: 1px solid black">
    <img width="200px" height="200px" src="{{ userOther.userAvatar }}" alt="">
    <h3>Name:</h3><p>{{ userOther.name }}</p>
    <h3>City:</h3><p>{{ userOther.userCity }}</p>
    <h3>Gender:</h3><p>{{ userOther.userGender }}</p>
</div>

{% endblock %}